### PR TITLE
Add `rmp-serde` support to heed-types.

### PR DESCRIPTION
**Pull request by aalekhpatel07**
# Pull Request

## Related issue
None, afaict.

## What does this PR do?
- Expose a utility struct that represents data that can be serialized and deserialized with [`rmp-serde`](https://github.com/3Hren/msgpack-rust/tree/master/rmp-serde).

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much @aalekhpatel07,

Seems great! Would it be possible to add an example or a test and to remove it from the default features, please?

**Comment by aalekhpatel07** [comment]
Absolutely!

Clippy didn't seem too happy about a couple of other spots. I think its a tiny change but if it adds too much noise to the diff, lmk and I'll revert it.

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you. It looks good to me but could you change the CI command that runs the examples and add `--all-festures`, please?

**Comment by aalekhpatel07** [comment]
Sure I could do that. Or if we don't want to enable all features for all the examples necessarily, we could also run the `rmp-serde` example separately. Thoughts?

**Comment by Kerollmops** [comment]
That's, indeed, much better 🙏

**Comment by aalekhpatel07** [comment]
Awesome! lmk if you need anything else on my end.

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Hey @aalekhpatel07 👋 Would it be possible to rebase on main? Sorry, I merged some PR 😬 I'll merge just after.

**Comment by aalekhpatel07** [comment]
For sure! Hopefully the rebase went fine.

**Review by Kerollmops — CHANGES_REQUESTED** [review]

**Comment by Kerollmops** [comment]
As I am the only one available on the team and the tests seem to pass, I will merge _by hand_ without approval 🆘

**Pull request merged**
