### PR TITLE
Remove mdbx support

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR removes every reference to the MDBX database, removing its support by the same, and updates the CI to only check the LMDB compilation.

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]

**Comment by Kerollmops** [comment]
bors merge

**Review by MarinPostma — APPROVED** [review]

**Comment by dvic** [comment]
May I ask what is the reason for removing mdbx support?

**Comment by dvic** [comment]
Thanks for clearing that up, makes sense!

**Comment by dvic** [comment]
By the way, the description of the repo still mentions mdbx :)

**Comment by Kerollmops** [comment]
Thank you very much, fixed!

**Pull request merged**
