### PR TITLE
Rework heed to be lightweight and simpler to maintain

### LINKED ISSUE #40: Document the safety issues with the unnamed database
LMDB have an important restriction on the unnamed database when named ones are opened, [the names of the named databases are stored as keys in the unnamed one and are immutable](http://www.lmdb.tech/doc/group__internal.html#gac08cad5b096925642ca359a6d6f0562a).

I faced a big bug that triggered a SIGSEGV when copying all of the entries of one unnamed database into another env, heed tried to write the values associated to the opened named databases multiple times, it triggered SIGSEGV sometimes.

I didn't took the time to reproduce this behavior but we must, at least, document it!

### LINKED ISSUE #56: Improve the poly/database length function
We currently create an iterator count the number of entries to returns to compute the number of entries a database stores.

There is a better way that is not `O(n)` which is using [the `num_entries` field of the `Stat` struct](https://github.com/mozilla/lmdb-rs/blob/df1c2f56e3088f097c719c57b9925ab51e26f3f4/lmdb-sys/src/bindings.rs#L182-L183) that is returned by [the `mdb_stat` function](https://github.com/mozilla/lmdb-rs/blob/df1c2f56e3088f097c719c57b9925ab51e26f3f4/lmdb-sys/src/bindings.rs#L882-L895).

### LINKED ISSUE #88: Support custom encoding/decoding errors
It would be better and easier to debug a program if the `BytesEncoding` and `BytesDecoding` traits could return any error type.

To do so we need to modify the `Error` enum and more specifically the `Encoding` and `Decoding` variants to wrap a `Box<dyn Error>`.

### LINKED ISSUE #94: Remove the generic types of the RoTxn and RwTxn
We introduce [a generic type to the RoTxn and RwTxn structs](https://github.com/Kerollmops/heed/blob/e7cd9f143834c750991cbe7e3d164e82799fdf33/heed/src/txn.rs#L9-L13) to make sure that we don't use a transaction created on one environment with another environment, this introduced [more methods on the Env struct to create typed transactions](https://github.com/Kerollmops/heed/pull/27/files#diff-4da8e8ee5c65a27bd048a2f2e55de0a9c75e87618fc02e17b235cc5413e625a0).

I am not quite sure it makes sense now that we added a runtime check to [make sure the transactions are valid and match the same environment](https://github.com/Kerollmops/heed/blob/e7cd9f143834c750991cbe7e3d164e82799fdf33/heed/src/database.rs#L228).

### LINKED ISSUE #127: Rework heed to be lightweight and simpler to maintain
- [x] Create a sub-crate for lmdb-sys in this repository, based on the `mdb.master.3` branch of LMDB.
- [x] Move from zerocopy to bytemuck (also related to licensing). https://github.com/meilisearch/heed/issues/82
- [ ] Be able to use `MDB_WRITEMAP` with heed to create databases. https://github.com/meilisearch/heed/pull/116
- [x] Remove the generic types of the `RoTxn` and `RwTxn`. https://github.com/meilisearch/heed/issues/94
- [ ] https://github.com/meilisearch/heed/issues/88. This is related to bytemuck. Don't forget to make `heed::Error: Send + Sync`.
- [x] Reintroduce a faster `Database::len` function. https://github.com/meilisearch/heed/issues/56
- [ ] Close all the issues/PRs that are related to MDBX as we no more support it and write about that in the README. https://github.com/meilisearch/heed/pull/125#issuecomment-1111910573
- [ ] Delete all of the branches that are not interesting anymore, and move from a `master` to a `main` branch.
- [ ] Document the safety issues with the unnamed database. https://github.com/meilisearch/heed/issues/40
- [ ] We should rework the usage of the `OwnedType` combined with `BEU32` types too!

### LINKED ISSUE #132: Make the `EnvOpenOption` available.
Currently, we can specify the `EnvOpenOption` when starting heed, but then we can’t query them.
It would be cool to have a wrapper around [`mdb_env_info`](http://www.lmdb.tech/doc/group__mdb.html#ga18769362c7e7d6cf91889a028a5c5947).

### LINKED ISSUE #138: Running the tests changes the test LMDB env files
When we run the test files, which are LMDB environments are modified. What I find strange is that tests must be reproducible and should not change the on-disk data or at least generate the same content.

```bash
cargo test
```

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR closes #127, closes #94, closes #56, closes #88, closes #40, closes #94, closes #132, closes #138.

- [x] Publish the _lmdb-master-sys_ crate to crates.io.
- [x] Use the published version of _lmdb-master-sys_ in heed.
- [x] Bump the version of _heed_, _heed-types_, and _heed-traits_ to crates.io.
- [x] Retrieve the latest commit of the _mdb.master_ LMDB branch.
- [x] Import https://github.com/meilisearch/heed/pull/142
- [x] Import #131 and #133
- [x] Expose a method to reserve a buffer for writing directly into it i.e. `MDB_RESERVE`.
- [x] Change the macro rule to be more explicit
- [x] Move to edition 2021
- [x] Replace the `BEU32` x `OwnedType` combo by new simpler codecs.
- [x] Read the LMDB documentation about aborting or committing read transactions, remove those methods from `RoTxn` is necessary.
- [x] The `RwTxn::abort` function, must not return a `Result` as LMDB can't fail when doing so.
- [x] The `BadOpenOptions` error must be more helpful and should maybe return the database with the expected options.
- [x] Implement `Debug` on most of the structs.
- [ ] https://github.com/meilisearch/heed/issues/144.
- [ ] Return an error if multiple transactions are open at the same time ([use thread local](https://doc.rust-lang.org/stable/std/macro.thread_local.html)).
- [x] Fix the generated test files issue. https://github.com/meilisearch/heed/issues/138
- [x] Cherry-pick fix of https://github.com/meilisearch/lmdb-rs/pull/11
- [ ] Document https://github.com/meilisearch/heed/issues/135#issuecomment-1313630140
- [x] Cherry-pick fix of https://github.com/meilisearch/heed/issues/136.
- [x] Remove the Fuchsia LICENSE.
- [ ] Remove the `OwnedType`s strange codecs.
- [x] Remove the double lifetime constraints from the `RwTxn`, the parent txn replaces the env one.
- [ ] Make the `RoTxn: Send + Sync` in `NO_TLS` mode, if possible, and rename the `sync-read-txn` feature flag.
- [ ] Bring [the caveats of LMDB](http://www.lmdb.tech/doc/index.html) (from the `mdb.master` branch) into the lib.rs documentation:
   - [ ] MacOs write transaction limits up to 10.
   - [ ] Windows no more than 64 environments at the same time.
   - [ ] Create a table?
- [x] Bring the documentation of LMDB into the bindings https://github.com/rust-lang/rust-bindgen/issues/955#issuecomment-1324190708

### CODE REVIEW

**Comment by arthurprs** [comment]
I was trying this branch yesterday and it was returning `MDB_PROBLEM` sometimes when committing whereas the main branch was working fine. I researched some more and it seems there's something off with this branch, but I can't tell what exactly.

For example, if you run `cargo run --example clear-database` and then try to stat the database with `mdb_stat target/clear-database.mdb` you get

```
mdb_env_open failed, error -30793 MDB_INVALID: File is not an LMDB file
```

whereas it works in the main branch it works as expected

```
Status of Main DB
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 1
```

Looking at the hexdump of the datafile you can see
```
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 08 00 00 00 00 00  de c0 ef be 02 00 00 00  |................|
```

but the main branch gives

```
00000000  00 00 00 00 00 00 00 00  00 00 08 00 00 00 00 00  |................|
00000010  de c0 ef be 01 00 00 00  00 00 00 00 00 00 00 00  |................|
```

Maybe I'm doing something stupid... but I wanted to mention in case I'm not.

**Comment by Kerollmops** [comment]
Hey @arthurprs,

Thank you very much for trying out this work-in-progress branch! I indeed had the same kind of issues and it looked like it was related to the fact that the folder to store the LMDB environment was already there, I fixed the whole list of tests by using a temporary directory. But it is very strange, I moved from the `master` to the `master3` branch of LMDB, maybe there is an issue when we use nested write transactions to create databases or environments.

**Comment by Kerollmops** [comment]
Hey @arthurprs,

Thank you again for testing this new branch, and for finding this potential issue.

Unfortunately, I wasn't able to trigger the same issue when using `mdb_stat` on a database created with the _clear-database_ example. I don't know if you notice but this branch is using the `mdb.master3` branch of LMDB which is incompatible with the previous version I was using i.e. `mdb.master`. If you want to use the right `mdb_stat` binary you can go to the _lmdb_master3_sys/lmdb/libraries/liblmdb_ folder and call `make`, the `mdb_stat` binary will be available in the folder.

I would be glad if you try out this branch and tell me whether your program is correctly working or is completely broken. Don't expect to be able to read a previous version of an LMDB database. Note that the API is changing a lot and I didn't document that for now, I will do it once this PR is merged.

**Comment by Kerollmops** [comment]
I am not sure about the reason why the multi-env test is broken and returns an _os error 22: invalid argument_ when calling the `clear` method.

https://github.com/meilisearch/heed/blob/98680acbc0846ea76780eee221190739482f52af/heed/examples/multi-env.rs#L33-L35

**Comment by Techie-Pi** [comment]
Hi! I've seen that this PR uses ``doxygen-rs``, and fyi I've just uploaded the crate to crates.io: https://crates.io/crates/doxygen-rs
Just in case you'd like to use that instead.

If you find any problem with the crate, feel free to open an issue or sending me a DM, I'll be more than happy to help! :)

**Comment by Kerollmops** [comment]
Thank you very much @Techie-Pi. I just updated the dependency to use a safer source which is crates.io 🙏

**Comment by Kerollmops** [comment]
For information, I will merge this PR with the `mdb.master` LMDB branch and not the `mdb.master3`, for now. I will bring `mdb.master3` and the encryption/decryption features in https://github.com/meilisearch/heed/pull/134 later. It will be easier for Meilisearch/milli to first try the new version of the library without bringing the new LMDB version for now, I prefer moving step by step.

**Comment by Kerollmops** [comment]
And here we are, [heed v0.20.0-alpha.0 just released on crates.io](https://crates.io/crates/heed/0.20.0-alpha.0) :tada:

**Pull request merged**
